name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 74.179.85.117 >> ~/.ssh/known_hosts

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest

      - name: Deploy app to Azure VM
        run: |
          ssh -i ~/.ssh/id_rsa nathanbale@74.179.85.117 << 'EOF'
            # Stop and remove container named "webapp" if it exists (running or not)
            container_id=$(docker ps -a --filter "name=webapp" --format "{{.ID}}")
            if [ -n "$container_id" ]; then
              docker stop $container_id || true
              docker rm $container_id || true
            fi

            # Pull and run the new container
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest
            docker run -d --name webapp -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest
          EOF
