name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging .
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging

      - name: SSH into staging server and deploy container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            # Create .env file with secret key on staging VM
            cat > ~/devops-webapp/.env << EOL
SECRET_KEY=${{ secrets.STAGING_SECRET_KEY }}
# Add other environment variables here as needed
EOL

            docker stop webapp-staging || true
            docker rm webapp-staging || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging
            docker run -d -p 8080:5000 --name webapp-staging --env-file ~/devops-webapp/.env ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging
