name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Install Python and dependencies for testing
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      # 🔐 SSH setup to connect to Azure VM
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 74.179.85.117 >> ~/.ssh/known_hosts

      # 🐳 Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🛠️ Build and push Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest

      # 🚀 Deploy to Azure VM via SSH
      - name: Deploy app to Azure VM
        run: |
          ssh -i ~/.ssh/id_rsa nathanbale@74.179.85.117 << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest
            docker stop webapp || true && docker rm webapp || true
            docker run -d --name webapp -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest
          EOF
