name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 74.179.85.117 >> ~/.ssh/known_hosts

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-webapp:latest

      - name: Deploy app on VM
        run: |
          scp -r . nathanbale@74.179.85.117:/home/nathanbale/devops-webapp
          ssh nathanbale@74.179.85.117 << 'EOF'
            cd devops-webapp
            docker build -t devops-webapp . 
            docker stop webapp || true && docker rm webapp || true
            docker run -d --name webapp -p 80:5000 devops-webapp
          EOF
