name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: 22
          script: |
            docker stop webapp-staging || true
            docker rm webapp-staging || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging

            echo "FLASK_ENV=staging" > .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

            docker run -d --env-file .env -p 8080:5000 --name webapp-staging ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging
