name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: 22
          script: |
            # Stop and remove any old container
            docker stop webapp-staging || true
            docker rm webapp-staging || true

            # Pull the latest staging image
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging

            # Recreate the .env file
            echo "FLASK_ENV=staging" > .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

            # Run container on port 8080 (mapped to Flask 5000)
            docker run -d \
              --env-file .env \
              -p 8080:5000 \
              --name webapp-staging \
              ${{ secrets.DOCKER_USERNAME }}/devops-webapp:staging
 

#Checkout code

#SSH into staging VM

#Stop and remove existing container (if any)

#Pull latest Docker image from Docker Hub

#Create a .env file

#Run the app with environment variables
