name: Deploy to Staging

on:
  push:
    branches:
      - staging
    paths:
      - '**'
      - '!**/production-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: azureuser
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: 22
          script: |
            docker stop webapp-staging || true
            docker rm webapp-staging || true
            docker pull nathanbale/devops-webapp:latest
            docker run -d -p 8080:5000 --name webapp-staging nathanbale/devops-webapp:latest
